layout: stacked
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: gautam-rai-physicist
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Quasicrystals
    web_url: https://www.vice.com/en_us/article/4x3me3/quasicrystals-are-natures-impossible-matter
    image_url: http://www-tc.pbs.org/prod-media/newshour/photos/2011/10/05/6214624380_ff0051258b_o_homepage_feature.jpg

  - name: Superconductivity
    web_url: https://home.cern/science/engineering/superconductivity
    image_url: https://singularityhub.com/wp-content/uploads/2018/05/search-high-temperature-superconductors-superconducting-223876228.jpg

  - name: Blender
    web_url: https://www.blender.org/
    image_url: https://download.blender.org/branding/community/blender_community_badge_white.png

theme: jekyll-theme-cayman
